### ISSUE TITLE
Clicking on the `t` in Star*t* Game autoselects the tower base behind it.

### ISSUE THREAD

**Issue by Dimonade** [mwbryant/bevy-tower-defense-tutorial#3]
Good day,

I have encountered a situation that when one clicks on the second `t` in *Start Game*, then when the game starts the tower base is already selected. Clicking on other locations of the *Start Game* buttons that do not have bases behind them do not select the spawn tower UI elements.

It is as if the main menu button allowing the clicks to bypass it.
Perhaps it is something related to `bevy_mod_picking` ignoring UI elements?

I did not have time to dig into that deeper, but I will read about it during the week hopefully.

Here is the area to click:
![2022-11-20-144046_194x105_scrot](https://user-images.githubusercontent.com/26929955/202905686-1bead24a-d095-41fc-9950-b9d33e3b4caf.png)

My system: Latest Manjaro (X and Wayland) and Gentoo (with Wayland).
If any more information is required, please let me know.
Thanks!

Edit:
Found the following [reddit thread](https://www.reddit.com/r/bevy/comments/vbll6b/capturing_mouse_clicks_in_the_ui_before_they_get/) and the corresponding [issue](https://github.com/bevyengine/bevy/issues/3570) in bevy.

**Comment by mwbryant** [comment]
Clicking through the UI is a problem in bevy that you need to handle carefully, however in this case we can solve this bug by just resetting mouse input when we exit the start menu.  I am addressing this in the next video and it's solved on that branch.
